#dist: trusty
#sudo: false

language: node_js
node_js:
  - "12"

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run build-campl-ngx
  - npm run test -- campl-ngx --no-progress  --watch=false --browsers=ChromeHeadless
#  - cd dist; npm dist
