#dist: trusty
#sudo: false

language: node_js
node_js:
  - "12"

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run build-campl-ngx
  - npm run test -- campl-ngx --no-progress  --watch=false --browsers=ChromeHeadless
#  - cd dist; npm dist

before_deploy:
  - cd projects/campl-ngx
  - npm pack

deploy:
  provider: release
  api_key: c7f0de16228970b8dd61321c4359c2cb1e50cdec
  file: projects/campl-ngx/*.tar.gz
  skip_cleanup: true
  draft: true
  #c7f0de16228970b8dd61321c4359c2cb1e50cdec
